<a href="https://colab.research.google.com/github/gonzaloangaut/NeuralNetworks/blob/main/Practicos/redes_neuronales_2023_practico_2_Angaut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Familiarizandose con **Numpy**

Referencias:
* https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python
* https://towardsdatascience.com/a-cheat-sheet-on-generating-random-numbers-in-numpy-5fe95ec2286

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays, `scipy` para operar con algebra lineal y `matplotlib.pyplot` para graficar.

In [ ]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

## **Ejercicio 2)** Creando arrays

**1)** Cree un array de enteros `a` a partir de la lista `[1,2,3]`.

**2)** Cree un array bidimensional de flotantes `b` a partir de la lista de listas `[[1.5,2,3],[4,5,6]]`.

**3)** Cree un array tridimensional de flotantes `c` a partir de la lista de listas `[[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]]`.

In [ ]:
# 2.1)
a = np.array([1,2,3])
print(a)
# 2.2)
b = np.array([[1.5,2,3],[4,5,6]], dtype = float)
print(b)
# 2.3)
c = np.array([[[1.5,2,3],[4,5,6]],[[3,2,1],[4,5,6]]], dtype = float)
print(c)

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


## **Ejercicio 3)** Inicializando arrays

**1)** Utilice `np.zeros` para crear un array bidimensional de flotantes incializados a `0.0`, y de dimensiones de tamaños `(3,4)`.

**2)** Utilice `np.ones` para crear un array tridimensional de enteros inicializados a `1`, y de dimensiones `(2,3,4)`.

**3)** Utilice `np.arange` para crear un array `d` de valores enteros equiespaciados de a `5` entre `10` y `25`.

**4)** Utilice `np.linspace` para crear un array de `9` valores flotantes equiespaciados entre `0.0` y `9.0`.

**5)** Utilice `np.full` para crear un array bidimensional llamado `e` de entradas iguales a `7`, y de dimesiones `(2,2)`.

**6)** Utilice `np.eye` para crear una matriz identidad llamada `f` de dimensiones 2x2.

**7)** Utilice `np.random.random` para crear un array bidimensional de dimensiones 2x2 inicializado con valores aleatorios uniformemente sorteados del intervalo $[0,1]$.

**8)** Utilice `np.empty` para crear un array bidimensional sin inicializar y de dimensiones `(3,2)`.


In [ ]:
# 3.1)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# 3.2)
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# 3.3)
d = np.arange(10, 25, 5)
d

array([10, 15, 20])

In [ ]:
# 3.4)
np.linspace(0, 9,9, dtype = float)

array([0.   , 1.125, 2.25 , 3.375, 4.5  , 5.625, 6.75 , 7.875, 9.   ])

In [ ]:
# 3.5)
e = np.full((2, 2), 7)
e

array([[7, 7],
       [7, 7]])

In [ ]:
# 3.6)
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [ ]:
# 3.7)
np.random.random((2,2))

array([[0.70934388, 0.951345  ],
       [0.45331002, 0.2270783 ]])

In [ ]:
# 3.8)
np.empty((3,2))

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])


## **Ejercicio 4)** Inspeccionando arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Utilizando `.shape`, determine cuales son las dimensiones del array `a`.

**2)** Utilizando la función `len()`, determine el *largo* del array `a`.

**3)** Utilizando `.ndim`, determine el número de dimensiones del array `b`.

**4)** Utilizando `.size`, determine el número de entradas que tienen `e`.

**5)** Utilizando `.dtype`, determine el tipo de los datos contenidos por el array `b`.

**6)** Utilizando `.dtype.name`, determine el nombre del tipo de los datos contenidos por el array `b`.

**7)** Utilizando `.astype`, convierta el array `b` a un array de tipo `int`.



In [ ]:
# 4.1)
np.shape(a)

(3,)

In [ ]:
# también se puede usar:
a.shape

(3,)

In [ ]:
# 4.2)
len(a)

3

In [ ]:
# 4.3)
b.ndim

2

In [ ]:
# 4.4)
e.size

4

In [ ]:
# 4.5)
b.dtype

dtype('float64')

In [ ]:
# 4.6)
b.dtype.name

'float64'

In [ ]:
# 4.7)
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

## **Ejercicio 5)** Tipos de datos

**1)** Cree un array que contenga elementos de tipo `np.int64`.

**2)** Cree un array que contenga elementos de tipo `np.float32`.

**3)** Cree un array que contenga elementos de tipo `np.complex128`.

**4)** Cree un array que contenga elementos de tipo `np.bool`.

**5)** Cree un array que contenga elementos de tipo `np.object`.

**6)** Cree un array que contenga elementos de tipo `np.string_`.

**7)** Cree un array que contenga elementos de tipo `np.unicode_`.

In [ ]:
# 5.1)
np.array(np.int64([1.32, 2.4]))

array([1, 2])

In [ ]:
# también se puede hacer:
np.array([1.32, 2.4], dtype=np.int64)

array([1, 2])

In [ ]:
# 5.2)
np.array([1.32, 2.4], dtype=np.float32)

array([1.32, 2.4 ], dtype=float32)

In [ ]:
# 5.3)
np.array([1.32, 2.4], dtype=np.complex128)

array([1.32+0.j, 2.4 +0.j])

In [ ]:
# 5.4)
np.array([True, False], dtype=bool)

array([ True, False])

In [ ]:
# notemos tambien:
np.array([1 == 1, 1 == 2], dtype=bool)

array([ True, False])

In [ ]:
# 5.5)
np.array([1, "hola"], dtype = object)

array([1, 'hola'], dtype=object)

In [ ]:
# 5.5)
array_string = np.array(["hola", "mundo"])
array_string

array(['hola', 'mundo'], dtype='<U5')

In [ ]:
np.array(["hola", 2], dtype = np.unicode_)

array(['hola', '2'], dtype='<U4')

## **Ejercicio 6)** Operando sobre arrays

Considere los arrays de los ejercicios 2) y 3).

**1)** Calcule la resta `a-b` de los arrays `a` y `b` y almacene el resultado en un array `g`.

**2)** Notar que `a` y `b` poseen diferentes dimensiones (i.e., `a.shape` es distinto de `b.shape`) y, sin embargo, en el inciso anterior numpy computa la resta `a-b`. Explique lo que ocurre.

**3)** Compare el anterior resultado con el uso de `np.substract`.

**4)** Calcule la suma `a+b` de los arrays `a` y `b`.

**5)** Compare el anterior resultado con el uso de `np.add`.

**6)** Calcule la división punto a punto  `a/b` de `a` y `b`.

**7)** Compare el anterior resultado con el uso de `np.divide`.

**8)** Calcule la multiplicación punto a punto  `a*b` de `a` y `b`.

**9)** Compare el anterior resultado con el uso de `np.multiply`.

**10)** Calcule la exponencial punto a punto  `np.exp(b)` de `b`.

**11)** Calcule la raíz cuadrada punto a punto  `np.sqrt(b)` de `b`.

**12)** Calcule el seno punto a punto  `np.sin(a)` de `a`.

**13)** Calcule el coseno punto a punto  `np.cos(b)` de `b`.

**14)** Calcule el logaritmo natural punto a punto  `np.log(a)` de `a`.

**15)** Calcule el producto punto `e.dot(f)` entre `e` y `f`.

**16)** Compare el anterior resultado con el uso de `np.dot`.

**17)** Explique las diferentes opciones que puede adoptar el producto punto de numpy según el número de dimensiones que tengan sus factores.

**Ayuda:** use https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [ ]:
# 6.1 y 2)
print(" a: ", a)
print(" b: ", b)
g = a-b
g

 a:  [1 2 3]
 b:  [[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
# notemos que lo que hizo fue armar una fila nueva a "a" igual a la primera

In [ ]:
# 6.3)
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
# hace lo mismo

In [ ]:
# 6.4)
a+b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
# 6.5)
np.add(a, b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
# 6.6)
a/b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
# 6.7)
np.divide(a, b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
# 6.8)
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
# 6.9)
np.multiply(a, b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
# 6.10)
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
# 6.11)
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
# 6.12)
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
# 6.13)
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [ ]:
# 6.14)
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
# 6.15)
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [ ]:
# 6.16)
np.dot(e, f)

array([[7., 7.],
       [7., 7.]])

In [ ]:
# es lo mismo

## **Ejercicio 7)** Comparando arrays

**1)** Use `==` para realizar una compación punto a punto de los arrays `a` y `b`.

**2)** Use `<` para realizar una comparación punto a punto del array `b` con el escalar `2`.

**3)** Use `np.array_equal(a,b)` para determinar si `a` y `b` son iguales como arrays.

In [ ]:
# 7.1)
a == b

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
# 7.2)
b<2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
# 7.3)
np.array_equal(a, b)

False

## **Ejercicio 8)** *Copiando* arrays

**1)** Use `.view()` para crear una vista del array `a`.

**2)** Use `.copy()` para crear una copa del array `a`.

In [ ]:
# 8.1)
np.ndarray.view(a)

array([1, 2, 3])

In [ ]:
# se puede hacer:
a.view()

array([1, 2, 3])

In [ ]:
# notar
a.view(dtype=np.int8) # los ceros son por los bits

array([1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0], dtype=int8)

In [ ]:
np.copy(a)

array([1, 2, 3])

## **Ejercicio 9)** Ordenado

**1)** Use `.sort()` para ordenar los elementos de `a`.

**2)** Ordene los elementos de `c` a lo largo del eje `0`. Explique.

In [ ]:
# 9.1)
np.sort(a)

array([1, 2, 3])

In [ ]:
# 9.2)
print("c es: ", c)
np.sort(c, axis = 0)

c es:  [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

## **Ejercicio 10)** Indexado y *slicing* (rebanado) de arrays

**1)** Seleccione el segundo elemento de `a`.

**2)** Seleccione el elemento en la fila 1 y columna 2 de `b`.

Si `n` y `m` son enteros, luego `[n:m]` indica el rango de índices que van desde `n` hasta `m-1`.

**3)** Seleccione el rango `[0:2]` de elementos de `a`.

**4)** Seleccione los elementos de `b` en el rango `[0:2]` de filas y la columna `1`.

**5)** Seleccione todos los elementos de `b` que esten en el rango de filas `[0:1]` y el rango completo de columnas.

**6)** Uso de *elipsis*. Seleccione los elementos de `c` indexados por `[1,...]`. Es esto lo mismo que lo indexado por `[1,:,:]`?

Si `n`, `m` y `s` son enteros, luego `[n:m:s]` indica el rango de índices que van desde `n` hasta `m-1` saltando de a `s` elementos.

**7)** Utilice lo mencionado anteriormente para acceder a los elementos de `a` de forma invertida.

**8)** Seleccione los elementos de `a` que sean menores que dos.

**9)** Seleccione los elementos de `b` indicados por la lista de índices `[(1,0),(0,1),(1,2),(0,0)]` utilizando, correspondientemente, una lista de indices fila y una lista de índices columna.

**10)** Utilizando una lista de indices fila, seleccione las filas `1,0,1,0` de `b`, y luego, para cada selección anterior, utilice una lista de índices columna para seleccionar las columnas `0,1,2,0`.

In [ ]:
# 10.1)
a[1]

2

In [ ]:
# 10.2)
b[1][2]

6.0

In [ ]:
# 10.3)
a[:2]

array([1, 2])

In [ ]:
# 10.4)
b[:2, 1]

array([2., 5.])

In [ ]:
# 10.5)
b[:1]

array([[1.5, 2. , 3. ]])

In [ ]:
# 10.6)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

In [ ]:
c[1, ...]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [ ]:
c[1, :, :]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [ ]:
# 10.7)
a

array([1, 2, 3])

In [ ]:
a[::-1]

array([3, 2, 1])

In [ ]:
# 10.8)
a[a<2]

array([1])

In [ ]:
# 10.9)
print(b)
b[[1, 0, 1, 0], [0, 1, 2, 0]]

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([4. , 2. , 6. , 1.5])

In [ ]:
# 10.10)
b[[1, 0, 1, 0]][:, [0, 1, 2, 0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## **Ejercicio 11)** transposición

**1)** Use `np.transpose()` para calcular la traspuesta del array `b`, y asignarlo a una variable `i`.

**2)** Use `.T` para acceder a `i` de forma traspuesta. Es esta forma traspuesta igual a `b`?

In [ ]:
# 11.1)
print(b)
i = np.transpose(b)
i

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [ ]:
# 11.2)
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## **Ejercicio 12)** Redimensionado

**1)** Use `.ravel()` para *achatar* el array `b`.

**2)** Use `.reshape()` para redimensionar el array `g` de manera que adquiera dimensiones especificadas por la tupla `(3,-2)`.

**3)** Que indica aquí el signo negativo del segundo índice?

In [ ]:
# 12.1)
np.ravel(b)

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [ ]:
# 12.2)
print(g)
np.reshape(g, (3, -2)) # que onda el -?

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## **Ejercicio 13)** Agregando y quitando elementos

**1) ¿HAY h?** Use `np.resize()` para crear a partir del array `h` un nuevo array de tamaño y dimensiones diferentes indicadas por `(2,6)`.

**2)** Use `np.append()` para crear un nuevo array que agrege los elementos de `g` al final de los elementos de `h`. Notar que `h` y `g` tienen diferentes dimensiones. Cómo resuelve `numpy` esta cuestión?

**3)** Use `np.insert()` para crear una copia de `a` en donde se inserta el número `5` en la posición indexada por `1`.

**4)** Use `np.delete()` para eliminar los elementos de `a` indicados por la lista de índices `[1]`.

In [ ]:
# 13.1) # uso b en lugar de h pq no tengo h
print(b)
np.resize(b, (2, 6))

[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[1.5, 2. , 3. , 4. , 5. , 6. ],
       [1.5, 2. , 3. , 4. , 5. , 6. ]])

In [ ]:
# 13.2)
print(a)
np.append(b, a) #use a pq tiene distinta dimension. lo achata

[1 2 3]


array([1.5, 2. , 3. , 4. , 5. , 6. , 1. , 2. , 3. ])

In [ ]:
# 13.3)
np.insert(a, 1, 5)

array([1, 5, 2, 3])

In [ ]:
# 13.4)
np.delete(a, [1])

array([1, 3])

## **Ejercicio 14)** Combinando arrays

**a)** Use `np.concatenate()` para concatenar los arrays `a` y `d`.

**b)** Use `np.vstack()` para apilar verticalmente los arrays `a` y `b`.

**c)** Use `np.row_stack()` para apilar verticalmente los arrays `e` y `f`.

**d)** Use `np.hstack()` para apilar horizontalmente los arrays `e` y `f`.

**e)** Use `np.column_stack()` para apilar horizontalmente los arrays `a` y `d`.

In [ ]:
# 14.a)
print(a)
print(d)
np.concatenate((a, d))

[1 2 3]
[10 15 20]


array([ 1,  2,  3, 10, 15, 20])

In [ ]:
# 14.b)
print(a)
print(b)
np.vstack((a, b))

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [ ]:
# 14.c)
print(e)
print(f)
np.row_stack((e, f))

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [ ]:
# 14.d)
print(e)
print(f)
np.hstack((e, f))

[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]


array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [ ]:
# 14.e)
print(a)
print(b)
#np.column_stack((a, b)) tienen que tener igual dimension

[1 2 3]
[[1.5 2.  3. ]
 [4.  5.  6. ]]


## **Ejercicio 15)** *Separando* arrays

**a)** Use `np.hsplit()` para separar horizontalmente el array `a` en 3 partes.

**b)** Use `np.vsplit()` para separar verticalmente el array `c` en 2 partes.

**c)** Cree el array `z` dado por

    [[1, 2, 3, 4],
      [2, 0, 0, 2],
      [3, 1, 1, 0]]

y sepárelo en dos partes a lo largo del eje `1`.

In [ ]:
# 15.a)
print(a)
np.hsplit(a, 3)

[1 2 3]


[array([1]), array([2]), array([3])]

In [ ]:
# 15.b)
print(c)
np.vsplit(c, 2)

[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 1.],
         [4., 5., 6.]]])]

In [ ]:
# 15.c)
z = np.array([[1, 2, 3, 4], [2, 0, 0, 2], [3, 1, 1, 0]])
print(z)
np.split(z, 2, axis=1)

[[1 2 3 4]
 [2 0 0 2]
 [3 1 1 0]]


[array([[1, 2],
        [2, 0],
        [3, 1]]),
 array([[3, 4],
        [0, 2],
        [1, 0]])]

## **Ejercicio 16)** Generando números aleatorios

**Faltan algunos**

**1)** Use `np.random.random()` para generar un número aleatorio de tipo float64 a partir de la distribución uniforme en $[0,1]$.

**2)** Use `np.random.random()` para crear un array de 10 números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**3)** Use `np.random.random()` para crear un array dos dimensional de dimensiones `(3,4)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución uniforme en $[0,1]$.

**4)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=0$ y de varianza $\sigma^2=1$.

**5)** Use `np.random.randn()` para generar un número aleatorio de tipo float64 a partir de la distribución normal centrada en $\mu=5$ y de varianza $\sigma^2=9$.

**6)** Use `np.random.randn()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo float64 generados a partir de la distribución normal centrada en $\mu=-1$ y de varianza $\sigma^2=2$.

**7)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{0,1,2,3\}$.

**8)** Use `np.random.randint()` para generar un número aleatorio de tipo int64 a partir de la distribución uniforme en $\{10,11,12,13,14,15\}$.

**9)** Use `np.random.randint()` para generar un array de dimensiones `(3,2,3)` conteniendo números aleatorios de tipo int64 generados a partir de la distribución uniforme en $\{0,1\}$.

**10)** Use `np.random.choice()` para seleccionar uniformemente al azar un elemento de la lista `["perro","gato","loro","caballo","vaca"]`.

**11)** Use `np.random.choice()` para crear un array de dimensiones `(3,3)` con selecciones generadas uniformemente al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]`.

**12)** Use `np.random.choice()` para crear un array de dimensiones `(3,3,3)` con selecciones generadas al azar de los elementos de la lista `["perro","gato","loro","caballo","vaca"]` de acuerdo a la correspondiente lista de probabilidades `[8/16,4/16,2/16,1/16,1/16]`.

**13)** Use `np.random.permutation()` generar una permutación, seleccionada uniformemente al azar una de las `n!` permutaciones que existen de un conjunto de `n` elementos, de una la lista de números entre `0` y `n-1` para `n=10` denominada `lista_n`.

**14)** Repita lo anterior usando `np.random.shuffle()` para aleatorizar la lista `lista_n` *in situ*.

In [ ]:
# 16.1)
np.random.random(1)

array([0.76591996])

In [ ]:
# 16.2)
np.random.random(10)

array([0.22055436, 0.91968387, 0.4383009 , 0.13410539, 0.30028774,
       0.67838962, 0.96367915, 0.63162516, 0.91361999, 0.87269117])

In [ ]:
# 16.3)
np.random.random((3, 4))

array([[0.56225603, 0.85290817, 0.47534306, 0.88282529],
       [0.70139166, 0.51192839, 0.86312597, 0.41123728],
       [0.49030514, 0.26957857, 0.63683844, 0.60076989]])

In [ ]:
# 16.4)
# uso sigma * np.random.randn(...) + mu
np.random.randn()

NameError: ignored

In [ ]:
# 16.5)
3*np.random.randn() + 5

4.988925696799516

In [ ]:
# 16.6)
np.sqrt(2)*np.random.randn(3, 2, 3)-1

array([[[-0.97117955, -1.0917609 , -3.13099854],
        [-1.8883922 , -0.27734629,  0.56754359]],

       [[ 0.93324182, -2.16178712, -2.40295125],
        [-1.60948231, -2.45648173,  1.41049785]],

       [[-0.30377318,  0.64265249, -1.51087385],
        [ 1.75281674, -1.49502572, -1.94586165]]])