<a href="https://colab.research.google.com/github/gonzaloangaut/NeuralNetworks/blob/main/Practicos/redes_neuronales_2023_practico_1_Angaut.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Familiarizandose con **Google Colab** y **Python**

## **Ejercicio 1)** Importando librerías

Importe las librerías `numpy` para operar con arrays y `matplotlib.pyplot` para graficar.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

## **Ejercicio 2)** Practicando instrucciones básicas

**1)** Ingrese un comentario

**2)** Implemente una suma, una multiplicación y una división entera.

**3)** Repita con números flotantes.

**4)** Ingrese un string.

**5)** Ingrese un docstring.

**6)** Concatene dos strings.

In [ ]:
# 2.1) esto es un comentario

In [ ]:
# 2.2)
1+1,5*3,3//2,3/2

(2, 15, 1, 1.5)

In [ ]:
# 2.3)
1.1+2.3, 3.2+3, 3.2*2.3, 5.3//2.3, 5.3/2.3

(3.4, 6.2, 7.359999999999999, 2.0, 2.3043478260869565)

In [ ]:
# 2.4)
"hola mundo"

'hola mundo'

In [ ]:
# 2.5)
"""hola
mundo"""

'hola\nmundo'

In [ ]:
# 2.6)
"hola" + "mundo"

'holamundo'

## **Ejercicio 3)** Practicando con variables

**1)** Inicialize una variable `x` con el valor `3`

**2)** Evalue la variable `x`.

**3)** Inicialize otra variable `y` con el valor `4` y evalue la suma de `x` con `y`.

**4)** Inicialize otra variable `z` con el resultado de evaluar `x*(2+y)`. Luego, evalúe `z`.

**5)** Inicialize una variable `s1` con el string `"hola"` y otra `s2` con el string  `"mundo"`.

**6)** Inicialize otra variable `s` con el resultado de concatenar `s1` con `s2`. Luego, evalùe `s`.

In [ ]:
# 3.1)
x = 3

In [ ]:
# 3.2)
x

3

In [ ]:
# 3.3)
y = 4
x + y

7

In [ ]:
# 3.4)
z = x*(2+y)
z

18

In [ ]:
# 3.5)
s1 = "hola"
s2 = "mundo"

In [ ]:
# 3.6)
s = s1 + s2
s

'holamundo'

## **Ejercicio 4)** Practicando igualdades y desigualdades

**1)** Evalúe `1 == 1`.

**2)** Evalúe `1 == 2`.

**3)** Evalúe `1 != 1`.

**4)** Evalúe `1 != 2`.

**5)** Evalúe `"hola" == "hola"`.

**6)** Evalúe `"hola" != "hola"`.

**7)** Evalúe `"hola" == "mundo"`.

**8)** Evalúe `"hola" != "mundo"`.

**9)** Evalúe `True == True`.

**10)** Evalúe `False == True`.

**11)** Evalúe `False != True`.

**12)** Evalúe `False == False`.

**13)** Evalúe `1 < 2`.

**14)** Evalúe `1 > 2`.

**15)** Evalúe `1 <= 2`.

**16)** Evalúe `1 >= 2`.

In [ ]:
# 4.1)
1 == 1

True

In [ ]:
# 4.2)
1 == 2

False

In [ ]:
# 4.3)
1 != 1

False

In [ ]:
# 4.4)
1 != 2

True

In [ ]:
# 4.5)
"hola" == "hola"

True

In [ ]:
# 4.6)
"hola" != "hola"

False

In [ ]:
# 4.7)
"hola" == "mundo"

False

In [ ]:
# 4.8)
"hola" != "mundo"

True

In [ ]:
# 4.9)
True == True

True

In [ ]:
# 4.10)
False == True

False

In [ ]:
# 4.11)
False != True

True

In [ ]:
# 4.12)
False == False

True

In [ ]:
# 4.13)
1<2

True

In [ ]:
# 4.14)
1>2

False

In [ ]:
# 4.15)
1<=2

True

In [ ]:
# 4.16)
1>=2

False

In [ ]:
# notemos tambien
True == 1

True

In [ ]:
False == 0

True

## **Ejercicio 5)** Practicando con la función `print`.

**1)** Imprima un número.

**2)** Imprima un string.

**3)** Imprima dos números.

**4)** Imprima dos strings.

**5)** Imprima dos strings con separador vacío.

**6)** Imprima un número y un string.

In [ ]:
# 5.1)
print(5)

5


In [ ]:
# 5.2)
print("hola")

hola


In [ ]:
# 5.3)
print(1, 54)

1 54


In [ ]:
# 5.4)
print("hola", "mundo")

hola mundo


In [ ]:
# 5.5)
print("hola", "mundo", sep="")

holamundo


In [ ]:
# 5.6)
print(3, "hola")

3 hola


## **Ejercicio 6)** Practicando con condicionales `if`, `else` y `elif`

**1)** Imprime algo el siguiente código?

      if 1 == 1:
          print("hola")

**2)** Y el siguiente código?

      if 1 != 1:
          print("hola")

**3)** Que imprime el siguiente código?

      if 1 == 2:
          print("hola")
      else:
          print("mundo")

**4)** Que imprime el siguiente código?

      if 1 == 2:
          print("hola")
      elif 1 < 2:
          print("mundo")
      else:
          print("argentina")

In [ ]:
# 6.1)
if 1 == 1:
  print("hola")

hola


In [ ]:
# 6.2)
if 1 != 1:
  print("hola")

In [ ]:
# 6.3)
if 1 == 2:
  print("hola")
else:
  print("mundo")

mundo


In [ ]:
# 6.4)
if 1 == 2:
  print("hola")
elif 1 < 2:
  print("mundo")
else:
  print("argentina")

mundo


## **Ejercicio 7)** Practicando con listas

**1)** Cree una lista con las siguientes strings `"perro"`, `"gato"`, `"loro"`, `"caballo"` y `"llama"`. Guardela en una variable llamada `animales`.

**2)** Acceda al 3er elemento de la lista.

**3)** Use slicing para acceder a los primeros 3 elementos de la lista.

**4)** Use slicing para acceder a los últimos 3 elementos de la lista.

**5)** Use slicing para acceder a los 3 elementos de la lista contando desde el segundo.

**6)** Use *list comprehension* para generar una lista con los animales que posean una letra `l` en su nombre.

**7)** Cree una lista con los números del 1 al 10, asignándola a una variable `a`.

**8)** Modifique la entrada `a[5]`, asignandole el nuevo valor `"hola"`. Luego, evalúe `a`.

**9)** Modifique las entradas `a[2:6]` con los valores de la lista `["perro", "gato","loro","caballo"]`. Luego, evalúe `a`.

In [ ]:
# 7.1)
animales = ["perro", "gato", "loro", "caballo", "llama"]
animales

['perro', 'gato', 'loro', 'caballo', 'llama']

In [ ]:
# 7.2)
animales[2]

'loro'

In [ ]:
# 7.3)
animales[0:3]

['perro', 'gato', 'loro']

In [ ]:
# tambien se puede ver
animales[:3]

['perro', 'gato', 'loro']

In [ ]:
# 7.4)
animales[2:5]

['loro', 'caballo', 'llama']

In [ ]:
# tambien se puede ver
animales[-3:]

['loro', 'caballo', 'llama']

In [ ]:
# 7.5)
animales[1:4]

['gato', 'loro', 'caballo']

In [ ]:
# 7.6)
lista=[animal for animal in animales if 'l' in animal]
lista

['loro', 'caballo', 'llama']

In [ ]:
# 7.7)
a=list(range(1,11))
a

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# 7.8)
a[5] = "hola"
a

[1, 2, 3, 4, 5, 'hola', 7, 8, 9, 10]

In [ ]:
# 7.9)
a[2:6]=["perro", "gato","loro","caballo"]
a

[1, 2, 'perro', 'gato', 'loro', 'caballo', 7, 8, 9, 10]

## **Ejercicio 8)** Practicando con tuplas

**1)** Determine si la tupla `(1,2,3)` es igual a si misma.

**2)** Determine si la tupla `(1,2,3)` es igual a la tupla `(1,2,3,4)`.

**3)** Inicialize una variable `t` con una tupla `(1,2,3)`. Luego, evalúe `t[0]`, `t[1]`, `t[2]` y `t[3]`.

**4)** Intente modificar el valor de `t[0]`.

**5)** Determine si la tupla `(1,2,3)` es igual a la lista `[1,2,3]`.

**6)** Inicialize las variables `x`, `y` y `z` asignando la tupla `"hola","mundo",100`. Evalúe `x`, `y` y `z`.

In [ ]:
# 8.1)
(1,2,3) == (1,2,3)

True

In [ ]:
# 8.2)
(1,2,3) == (1,2,3,4)

False

In [ ]:
# 8.3)
t = (1,2,3)
t[0]

1

In [ ]:
t[0], t[1], t[2] # no hay t[3]

(1, 2, 3)

In [ ]:
# 8.4)
#t[0] = 912
# la tupla no soporta asignar item

In [ ]:
# 8.5)
(1, 2, 3) == [1, 2, 3]

False

In [ ]:
# 8.6)
x="hola"
y="mundo"
z=100
(x,y,z)

('hola', 'mundo', 100)

## **Ejercicio 9)** Practicando con loops

**1)** Implemente un loop usando la instrucción `for` que imprima los números pares desde el 0 hasta el 10.

**2)** *Conjetura de Collatz:* Implemente un loop usando la instrucción `while` calcule la iteración

\begin{equation}
n_{t+1} = f(n_t)
\end{equation}

donde $f(n) = n/2$ si $n$ es par y $f(n)=3n+1$ si $n$ es impar, partiendo de $n_0=10$. El loop debe detenerse cuando se cumple la condición $n_t=1$ para algún $t$. Que observa? Comente. Cuantas iteraciones realiza el loop?

**3)** Use `for` para iterar sobre la lista `["perro","gato","loro","caballo","llama"]`, imprimiendo los cada item en cada iteración.

In [ ]:
# 9.1)
for i in range(0,11):
  if i%2==0:
    print(i)

0
2
4
6
8
10


In [ ]:
# 9.2)
n=10
contador=0
while n!=1:
  if n%2==0:
    n=n/2
  else:
    n=3*n+1
  contador=contador+1

print("Hace ", contador, " iteraciones")

Hace  6  iteraciones


In [ ]:
# 9.3)
animales = ["perro","gato","loro","caballo","llama"]

for animal in animales:
  print(animal)

perro
gato
loro
caballo
llama


## **Ejercicio 10)** Definiendo y evaluando funciones

**1)** Implemente una función llamada `suma` que retorne la sume dos números. Testeela.

**2)** Implemente una función llamada `opcional` que adopte dos parámetros de entrada, y que el segundo de ellos sea opcional con un valor por defecto igual a 1. La función debe retornar la resta de ambos números. Testeela.

**3)** Implemente una función llamada `fact` que calcule y retorne el factorial de un número `n` si es que `n` es natural o zero. En caso contrario, que imprima el mensaje "El número n no es un entero no negativo." y retorne `None`. Testeela.

In [ ]:
# 10.1)
def suma(a,b):
  return a+b
c = suma(13,54)
c

67

In [ ]:
# 10.2)
def opcional(a, b=1):
  return a-b

c=opcional(13, 5)
d=opcional(6)

c, d

(8, 5)

In [ ]:
# 10.3)
def fact(n):
  if n==0 or (isinstance(n, int) and n>0):
    factorial = 1
    for i in range(1, n+1):
      factorial=factorial*i
    return factorial
  else:
    print("El numero no es un entero no negativo")
    return None

print(fact(8))
print(fact(12.5))
print(fact(-8))

40320
El numero no es un entero no negativo
None
El numero no es un entero no negativo
None


## **Ejercicio 11)** Practicando con arrays

**1)** Inicialize un array de enteros a partir de la lista `[1,2,3]`. Llamelo `b`.

**2)** Inicialize un array 2-dimensional a partir de las listas anidadas `[[1,2,3],[4,5,6],[7,8,9]]`. Llamelo `a`.

**3)** Acceda a la entrada de la fila $i=1$ y la columna $j=2$ del array `a`.

**4)** Inicialice un array de 10 valores 0 en representacón flotante de 64 bits.

**5)** Inicialice un array de 10 valores 3.14 en representacón flotante de 32 bits.

In [ ]:
# 11.1)
lista = [1, 2, 3]
b=np.array([])
for elem in lista:
  b=np.append(b, elem)
b

array([1., 2., 3.])

In [ ]:
# es mas facil:
b=np.array([1, 2, 3])
b

array([1, 2, 3])

In [ ]:
# 11.2)
lista_1 = [1,2,3]
lista_2 = [4,5,6]
lista_3 = [7,8,9]
lista = [lista_1,lista_2,lista_3]

a = np.concatenate([[lista_1], [lista_2], [lista_3]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# es mas facil:
a = np.array([[1,2,3], [4,5,6], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 6]])

In [ ]:
# 11.3)
a[1][2]

6

In [ ]:
# 11.4)
a=np.float64(0)
ceros=np.array([a]*10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# esto tambien puede hacerse de la siguiente forma:
np.zeros(10, dtype=np.float64)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 11.5)
a=np.float32(3.14)
pi=np.array([a]*10)
pi

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
      dtype=float32)

In [ ]:
# esto tambien puede hacerse de la siguiente forma:
3.14*np.ones(10, dtype=np.float32)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
      dtype=float32)

## **Ejercicio 12)** Practicando con clases

**1)** Defina una clase llamada `MiClase` que posea una variable miembro llamada `nombre`. El inicializador `__init__()` de la clase debe poseer un argumento opcional, que debe usarse para inicializar el valor de la variable miembro `nombre` con el valor por defecto `"mi clase"`.

**2)** Agregue a la clase la función miembro `__str__()` que retorne el valor de la variable miembro `nombre`.

**3)** Cree un objeto de la clase en cuestión y de nombre `mi_objeto`, y testee la función `__str__()` evaluando la expresión `str(mi_objeto)`.

**4)** Agregue a la clase la función `__len__()` que retorne el largo de la variable miembro `nombre`. Testee dicha función.

**5) NO SALIÓ** Agregue a la clase una función miembro llamada `cambiar_nombre` que sirva para cambiar el valor de la variable miembro `nombre`. Testee dicha función.

In [ ]:
# 12.1 y otros)
class MiClase:
  def __init__(self, nombre = "mi clase"):
    self.nombre = nombre

  def __str__(self):
    return self.nombre

  def __len__(self):
    return len(self.nombre)


In [ ]:
# 12.3)
mi_objeto = MiClase("mi objeto")
str(mi_objeto)

'mi objeto'

In [ ]:
# 12.4)
len(mi_objeto)

9

## **Ejercicio 13)** Graficando

**1)** Utilice `np.linspace` para generar un array de 100 valores equidistantes entre 0 y 5. Almacene el array en una variable `valores_x`.

**2)** Calcule el array llamado `valores_y1` de valores `np.cos(x)` para cada `x` en `valores_x`.

**3)** Calcule el array llamado `valores_y2` de valores `np.sin(x)` para cada `x` en `valores_x`.

**4)** Use estos arrays para graficar, con curvas, las funciones $\cos(x)$ y $\sin(x)$ en el rango $[0,5]$. Use una línea contínua para el coseno y una punteada para el seno.

**5)** Acomode el gráfico: agregue etiquetas a los ejes y a las curvas. Modifique los límites del área graficada para que se vean correctamente las curvas. Agregue un título a la figura.

In [ ]:
# 13.1)
valores_x = np.linspace(0, 5, 100)

In [ ]:
# 13.2 y 3)
valores_y1 = [np.cos(x) for x in valores_x]
valores_y2 = [np.sin(x) for x in valores_x]


In [ ]:
# 13.4 y 5)
plt.plot(valores_x, valores_y1, label="cos(x)")
plt.plot(valores_x, valores_y2, label="sin(x)", linestyle="dotted")
plt.xlabel("Eje x")
plt.ylabel("Eje y")
plt.legend()
plt.show()

NameError: ignored